// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCODC1oY8a1SothZdhDjYa6I0VjJLxmTV8',
    appId: '1:1044448088575:web:059b68a7158423bc5d97ca',
    messagingSenderId: '1044448088575',
    projectId: 'unihub-a534c',
    authDomain: 'unihub-a534c.firebaseapp.com',
    storageBucket: 'unihub-a534c.firebasestorage.app',
    measurementId: 'G-9JLXLN8733',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYl5FaXpiGjKjRKAidyrnXWxL7lti2CcU',
    appId: '1:1044448088575:android:0d5f73650ffec8205d97ca',
    messagingSenderId: '1044448088575',
    projectId: 'unihub-a534c',
    storageBucket: 'unihub-a534c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGafrJ7-6qJW-S-qr0BXArsod-j_AKTUQ',
    appId: '1:1044448088575:ios:b715b5aceccc214a5d97ca',
    messagingSenderId: '1044448088575',
    projectId: 'unihub-a534c',
    storageBucket: 'unihub-a534c.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );
}
